spring:
  application:
    name: springboot-bwl
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uniapp_database?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789

#web
server:
  port: 8099
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: utf-8
      force: true

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true